---
- name: "Load settings for the fixpermissions role"
  include_vars: "{{ host }}.yml"
# Change group of the site tld
- name: Change group of the site's group recursively
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}'
    group: root
    recurse: yes
  become: true

# Change group of the site tld
- name: Change group of the site's tld
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}'
    group: apache
  become: true

# Change ownership of the site recursively
- name: Change ownership of the site recursively
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}'
    owner: '{{ owner }}'
    recurse: yes
  become: true

# Change ownership of sites sites
- name: Change ownership of sites only
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}/sites'
    group: apache
    mode: 0775
  become: true

# Change ownership of sites/default
- name: Change ownership of sites/default only
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}/sites/default'
    group: apache
    mode: 0775
  become: true

# Change ownership of sites/default/files recursively
- name: Change ownership of sites/default/files recursively
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}/sites/default/files'
    group: apache
    mode: 0775
    recurse: yes
  become: true

# Change group of the site's settings.php
- name: Change group of the sites/default/settings.php
  file:
    path: '{{ fixpermissions_conf.d7webdir }}{{ sitename }}/sites/default/settings.php'
    group: apache
  become: true

# Clear the drupal cache
- name: Clear the drupal cache
  shell: "drush @{{ sitename }}-{{ item }} cc all"
  become: true
  with_items: "{{ fixpermissions_conf.alias }}"

# Import the sql dump
- name: Clear the drupal registry
  shell: "drush @{{ sitename }}-{{ item }} rr"
  become: true
  with_items: "{{ fixpermissions_conf.alias }}"
