---
- hosts: '{{ host }}'
  # become: true
  tasks:
    # Copy the db, site files and configuration to local temporary directory
    - name: Push site directory from local host to remote host
      synchronize:
        mode: push
        dest: '/cwis/http/htdocs/{{ sitename }}'
        src: site/
        delete: yes
        rsync_path: "sudo -i rsync"

    - name: Push site configuration from local host to remote host
      synchronize:
        mode: push
        dest: '/etc/httpd/conf.d/drupal-available/{{ sitename }}.conf'
        src: 'configuration/{{ sitename }}.conf'
        delete: yes
        rsync_path: "sudo -i rsync" 

    # Grab the DB credentials
    - name: Register db name as variable
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $2}' | sed 's/--database=//g'
      register: mysql_database_name
      become: true

    - name: Register host name as variable
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $3}' | sed 's/--host=//g'
      register: mysql_host_name
      become: true

    - name: Register user name as variable
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $4}' | sed 's/--user=//g'
      register: mysql_user_name
      become: true

    - name: Register password
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $5}' | sed 's/--password=//g'
      register: mysql_password
      become: true

    # prod
    # - name: Register database name as variable on prod
    #   shell: drush @'{{ sitename }}'-prod sql-connect | awk '{print $2}' | sed 's/--database=//g'
    #   become: true
    #   register: mysql_database_name
    #   when: host == "web-4"

    # - name: Register host name as variable on prod
    #   shell: drush @'{{ sitename }}'-prod sql-connect | awk '{print $3}'
    #   become: true
    #   register: mysql_host_name
    #   when: host == "web-4"

    # - name: Register user name as variable on prod
    #   shell: drush @'{{ sitename }}'-prod sql-connect | awk '{print $4}'
    #   become: true
    #   register: mysql_user_name
    #   when: host == "web-4"

    # - name: Register password as variable on prod
    #   shell: drush @'{{ sitename }}'-prod sql-connect | awk '{print $5}'
    #   become: true
    #   register: mysql_password
    #   when: host == "web-4"
    
    # - name: debug
    #   debug:
    #     msg: "mysql user name {{ mysql_database_name.stdout }}"


    # Import the db dump
    - name: Import site DB from file to mysql
      mysql_db:
        state: import
        name: '{{ mysql_database_name.stdout }}'
        login_host: '{{ mysql_host_name.stdout }}'
        login_user: '{{ mysql_user_name.stdout }}'
        login_password: '{{ mysql_password.stdout }}'
        target: '/cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'
      become: true
      when: host == 'dev' or host == 'staging'

    # PROD import the db dump
    # - name: Import site DB using drush
    #   shell: 'drush @{{ sitename }}-prod sqlc < /cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'
    #   become: true
      


    # Cleanup    
    - name: Remove remote db dump
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'
        state: absent
      become: true

    # Set Dest permissions
    # Change group of the site tld
    - name: Change group of the site's group recursively
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}'
        group: root
        recurse: yes
      become: true

    # Change group of the site tld
    - name: Change group of the site's tld
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}'
        group: apache
      become: true

    # Change ownership of the site recursively
    - name: Change ownership of the site recursively
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}'
        owner: '{{ owner }}'
        recurse: yes
      become: true

    # Change group of the site's settings.php
    - name: Change group of the sites/default/settings.php
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}/sites/default/settings.php'
        group: apache
      become: true

    # Enable site using existing script.
    - name: Enable site
      shell: '/usr/local/drupal-tools/ensite {{ sitename }}'
      become: true

    # Clear site cache and rebuild registry  
    - name: Clear site cache
      shell: drush @'{{ sitename }}'-'{{ host }}' cc all
      become: true

    - name: Rebuild registry
      shell: drush @'{{ sitename }}'-'{{ host }}' rr
      become: true