---
- hosts: '{{ host }}'
  # become: true
  tasks:
    # Copy the db, site files and configuration to local temporary directory
    - name: Push site directory from local host to remote host
      synchronize:
        mode: push
        dest: '/cwis/http/htdocs/{{ sitename }}'
        src: site/
        delete: yes
        rsync_path: "sudo -i rsync"

    - name: Push site configuration from local host to remote host
      synchronize:
        mode: push
        dest: '/etc/httpd/conf.d/drupal-available/{{ sitename }}.conf'
        src: 'configuration/{{ sitename }}.conf'
        delete: yes
        rsync_path: "sudo -i rsync" 

    # Grab the DB credentials
    - name: Register db name as variable
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $2}' | sed 's/--database=//g'
      register: mysql_database_name
      become: true

    - name: Register host name as variable
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $3}' | sed 's/--host=//g'
      register: mysql_host_name
      become: true

    - name: Register user name as variable
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $4}' | sed 's/--user=//g'
      register: mysql_user_name
      become: true

    - name: Register password
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $5}' | sed 's/--password=//g'
      register: mysql_password
      become: true
    
    # - name: debug
    #   debug:
    #     msg: "mysql user name {{ mysql_database_name.stdout }}"


    # Import the db dump
    - name: Import site DB from file to mysql
      mysql_db:
        state: import
        name: '{{ mysql_database_name.stdout }}'
        login_host: '{{ mysql_host_name.stdout }}'
        login_user: '{{ mysql_user_name.stdout }}'
        login_password: '{{ mysql_password.stdout }}'
        target: '/cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'


    # Cleanup    
    - name: Remove remote db dump
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'
        state: absent
      # become: true

