---
- hosts: '{{ host }}'
  # become: true
  tasks:
    # Empty tmp folders
    - name: Empty the local site folder
      file:
        path: site/
        state: absent
      delegate_to: localhost
      become: true

    - name: Empty the local config folder
      file:
        path: configuration/
        state: absent
      delegate_to: localhost
      become: true
      
    # Recreate tmp folders because emptying them also deletes them
    - name: Create the local site folder
      file:
        path: site
        owner: hdyami
        group: hdyami
        mode: 0755
        state: directory
      delegate_to: localhost

    - name: Create the local config folder
      file:
        path: configuration
        owner: hdyami
        group: hdyami
        mode: 0755
        state: directory
      delegate_to: localhost

    # Grab the DB credentials
    - name: Register list of mysql credentials for given site
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $2}' | sed 's/--database=//g'
      register: mysql_database_name

    - name: Register list of mysql credentials for given site
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $3}' | sed 's/--host=//g'
      register: mysql_host_name

    - name: Register list of mysql credentials for given site
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $4}' | sed 's/--user=//g'
      register: mysql_user_name

    - name: Register list of mysql credentials for given site
      shell: drush @'{{ sitename }}'-'{{ host }}' sql-connect | awk '{print $5}' | sed 's/--password=//g'
      register: mysql_password

    # Create a db dump remotely
    - name: Dump site DB into a file in the site directory on the remote host
      mysql_db:
        state: dump
        name: '{{ mysql_database_name.stdout }}'
        login_host: '{{ mysql_host_name.stdout }}'
        login_user: '{{ mysql_user_name.stdout }}'
        login_password: '{{ mysql_password.stdout }}'
        target: '/cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'

    # Copy the db, site files and configuration to local temporary directory
    - name: Pull site directory from remote host to local host
      synchronize:
        mode: pull
        src: /cwis/http/htdocs/'{{ sitename }}'/
        dest: site
        rsync_path: "sudo -i rsync"

    - name: Pull site configuration from remote host to local host
      synchronize:
        mode: pull
        src: /etc/httpd/conf.d/drupal-available/'{{ sitename }}'.conf
        dest: configuration
        rsync_path: "sudo -i rsync" 
    # Cleanup    
    - name: Remove the remote db dump
      file:
        path: '/cwis/http/remote/htdocs/{{ sitename }}/{{ sitename }}_drpl.sql'
        state: absent
      # become: true