---
# backup a site
- name: "Load settings for the localtoremote role"
  include_vars: "{{ host }}.yml"

# Make sure everything in the local site container folder is readable by the user invoking ansible-playbook
- name: Make sure everything in the local site container folder is readable by the user invoking ansible-playbook
  file:
    path: site/
    # state: directory
    recurse: yes
    mode: "u+wr"
  delegate_to: localhost

# Copy the db, site files and configuration to local temporary directory
- name: Push site directory from local host to remote host
  synchronize:
    mode: push
    dest: '{{ localtoremote_conf.d7webdir }}{{ sitename }}'
    src: site/
    delete: yes
    rsync_path: "sudo -i rsync"
  become: true

- name: Push site configuration from local host to remote host
  synchronize:
    mode: push
    dest: '/etc/httpd/conf.d/drupal-available/{{ sitename }}.conf'
    src: 'configuration/{{ sitename }}.conf'
    delete: yes
    rsync_path: "sudo -i rsync"
  become: true

# Import the sql dump
- name: Import the sql dump
  shell: "drush @{{ sitename }}-{{ item }} sqlc < {{ localtoremote_conf.d7webdir }}{{ sitename }}/{{ sitename }}_drpl.sql"
  become: true
  with_items: "{{ localtoremote_conf.alias }}"

# - name: debug
#   debug:
#     msg: "mysql user name {{ mysql_database_name.stdout }}"

# Cleanup    
- name: Remove remote db dump
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}/{{ sitename }}_drpl.sql'
    state: absent
  become: true

# Change group of the site tld
- name: Change group of the site's group recursively
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}'
    group: root
    recurse: yes
  become: true

# Change group of the site tld
- name: Change group of the site's tld
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}'
    group: apache
  become: true

# Change ownership of the site recursively
- name: Change ownership of the site recursively
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}'
    owner: '{{ owner }}'
    recurse: yes
  become: true

# Change ownership of sites sites
- name: Change ownership of sites only
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}/sites'
    group: apache
    mode: 0775
  become: true

# Change ownership of sites/default
- name: Change ownership of sites/default only
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}/sites/default'
    group: apache
    mode: 0775
  become: true

# Change ownership of sites/default/files recursively
- name: Change ownership of sites/default/files recursively
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}/sites/default/files'
    group: apache
    mode: 0775
    recurse: yes
  become: true

# Change group of the site's settings.php
- name: Change group of the sites/default/settings.php
  file:
    path: '{{ localtoremote_conf.d7webdir }}{{ sitename }}/sites/default/settings.php'
    group: apache
  become: true

# Change ownership of the site's configuration
- name: Change ownership of the site's configuration
  file:
    path: '/etc/httpd/conf.d/drupal-available/{{ sitename }}.conf'
    owner: root
    group: root
  become: true

# Clear the drupal cache
- name: Clear the drupal cache
  shell: "drush @{{ sitename }}-{{ item }} cc all"
  become: true
  with_items: "{{ localtoremote_conf.alias }}"

# Import the sql dump
- name: Clear the drupal registry
  shell: "drush @{{ sitename }}-{{ item }} rr"
  become: true
  with_items: "{{ localtoremote_conf.alias }}"

# Enable site using existing script.
- name: Enable site
  shell: '/usr/local/drupal-tools/ensite {{ sitename }}'
  become: true