---
- hosts: umwebdev
  user: hdyami
  tasks:
    - name: Copy the site from dev to local temporary directory
      synchronize: src=/cwis/http/htdocs/hdyami dest=/home/hailu/ansible/tmp
      become: true
      become_method: sudo
      become_user: root
      become_flags: '-i'

...